import type { Metadata } from "next";
import { DotGothic16 } from 'next/font/google'; 
import './globals.css';

const dotGothic16 = DotGothic16({
  weight: ['400'],        
  subsets: ['latin'],     
  display: 'swap',         
});

//Webページの<head>タグ内に記述される情報
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      {/* 3. classNameをbodyタグに渡す */}
      <body className={dotGothic16.className}>
        {children}
      </body>
    </html>
  );
}
