import type { Metadata } from "next";
import { DotGothic16 } from "next/font/google";
import "./globals.css";
import Header from "@/app/components/Header";
import { AuthProvider } from "@/hooks/useAuth";

const dotGothic16 = DotGothic16({
  weight: ["400"],
  subsets: ["latin"],
  display: "swap",
});

//Webページの<head>タグ内に記述される情報
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      {/* 3. classNameをbodyタグに渡す */}
      <body className={dotGothic16.className}>
        <AuthProvider>
          <Header />
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
